### ISSUE TITLE
Share License Information

### ISSUE THREAD

**Issue by sudheerpalyam** [sqlparser/gsp_demo_java#9]
Really impressed with the functionality provided by this project. Considering to see if we can use this to extract lineage from Hive Sql Queries. Is this project opensource? How about the underline gudusoft.gsqlparser-2.0.6.5.jar, is this allowed to be used in a enterprise?

**Comment by sqlparser** [comment]
You need a developer license in order to use the GSP library in your project:
http://support.sqlparser.com/gsp-faq.html#q-whats-kind-of-general-sql-parser-license-do-i-need

http://sqlparser.com/order.php
